#!/bin/bash

# Returning a boolean from a bash function
#   [Solved]: Stack Overflow: https://stackoverflow.com/questions/5431909/returning-a-boolean-from-a-bash-function
#
is_docker_installed() {
  which docker >> /dev/null 2>&1
  if [ "$?" != "0" ]; then
    log::debug "[is_docker_installed] Docker not found"
    return 1
  fi

  DOCKER_VERSION=$(get_docker_version)
  log::info "Docker Installed(version: ${DOCKER_VERSION})"
  return 0
}

get_docker_version() {
  echo $(docker version -f {{.Client.Version}})
}

is_network_exist() {
  sudo docker network inspect $PACKAGE_DOCKER_DEFAULT_NETWORK >>/dev/null 2>&1
  if [ "$?" = "0" ]; then
    echo "true"
  else
    echo "false"
  fi
}

create_network() {
  # sudo docker network inspect $PACKAGE_DOCKER_DEFAULT_NETWORK >>/dev/null 2>&1
  # if [ "$?" != "0" ]; then
  #   sudo docker network create $PACKAGE_DOCKER_DEFAULT_NETWORK
  # fi

  if [ "$(is_network_exist)" = "false" ]; then
    log::info "Create Network: ${PACKAGE_DOCKER_DEFAULT_NETWORK}"
    sudo docker network create $PACKAGE_DOCKER_DEFAULT_NETWORK >> /dev/null 2>&1
  fi
}

try_to_remove_podman() {
  which podman >>/dev/null 2>&1
  if [ "$?" = "0" ]; then
    log::info "Found podman, removing ..."
    pm remove -y podman

    # Clean
    #   1. docker
    sudo rm -rf `which docker`

    # log::info "Upgrade Docker ..."
  fi
}

install_docker_core() {
  # Returning a boolean from a bash function
  #   Useage
  if is_docker_installed; then
    create_network
    return 
  fi

  log::info "Install Docker ..."
  if [ "$(os::is_macos)" = "true" ]; then
    # MacOS
    # 1. CLI
    brew install docker
    # 2. Runtime
    brew install colima
    # 3. Start
    colima start --cpu 4 --memory 8 --disk 100
  else
    # Linux
    sudo curl -fsSL https://get.docker.com -o $PACKAGE_DOCKER_TMP_INSTALL_SCRIPT
    sudo sh $PACKAGE_DOCKER_TMP_INSTALL_SCRIPT
    # Role
    sudo usermod -aG docker $USER
    # Clean
    sudo rm -f $PACKAGE_DOCKER_TMP_INSTALL_SCRIPT
  fi
}

install_docker_cli_only() {
  local DOCKERVERSION=20.10.14
  local tmp_download_dir=

  if [ "$(os::has_command os::tmp_dir)" = "true" ]; then
    tmp_download_dir=$(os::tmp_dir)
  else
    tmp_download_dir=/tmp/tmp_download_dir
  fi

  mkdir -p $tmp_download_dir
  cd $tmp_download_dir
  curl -fSLO https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKERVERSION}.tgz
  sudo tar xzvf docker-${DOCKERVERSION}.tgz --strip 1 -C /usr/local/bin docker/docker
  sudo rm docker-${DOCKERVERSION}.tgz
  cd - >> /dev/null 2>&1
  rm -rf $tmp_download_dir
}

start_docker() {
  if [ "$(os::is_macos)" = "true" ]; then
    return
  fi

  # Linux
  sudo systemctl status docker >> /dev/null 2>&1
  if [ "$?" != "0" ]; then
    log::info "Start Docker daemon ..."

    sudo systemctl enable docker
    sudo systemctl start docker
  fi

  # @TODO create default network
  # sudo docker network create compose-ingress
  if [ "$(is_network_exist)" = "false" ]; then
    log::info "Create Network: ${PACKAGE_DOCKER_DEFAULT_NETWORK}"
    sudo docker network create $PACKAGE_DOCKER_DEFAULT_NETWORK >> /dev/null 2>&1
  fi
}

stop_docker() {
  sudo systemctl stop docker
  sudo systemctl disable docker
}

remove_docker_core() {
  pm remove -y docker-ce docker-ce-cli containerd.io
}

install() {
  if [ "$(os::is_docker)" = "true" ]; then
    log::warn "You are in docker env."

    if [ "$(os::has_command docker)" = "false" ]; then
      log::info "Install Docker CLI Only ..."
      install_docker_cli_only
    fi

    # # if [ ! -f "/var/run/docker.sock" ]; then
    # file /var/run/docker.sock >> /dev/null 2>&1
    # if [ "$?" != "0" ]; then
    #   log::error "You have not binded /var/run/docker.sock."
    #   exit 1
    # fi
    return 
  fi

  try_to_remove_podman

  install_docker_core

  start_docker
}

remove() {
  try_to_remove_podman

  # Returning a boolean from a bash function
  #   Useage
  if ! is_docker_installed; then
    log "Cannot found docker or docker has been already removed before."
    exit 0
  fi

  log "Stop Docker Daemon ..."
  stop_docker

  log "Remove Docker ..."
  remove_docker_core
}

export -f is_docker_installed
export -f get_docker_version
export -f is_network_exist
export -f create_network
export -f try_to_remove_podman
export -f install_docker_core
export -f start_docker
export -f stop_docker
export -f remove_docker_core

export -f install
export -f remove

export -f install_docker_cli_only
